### ISSUE TITLE
setup autorelease on main

### ISSUE THREAD

**Issue by tabrindle** [tabrindle/envinfo#109]

**Comment by gengjiawen** [comment]
Any thought on trying Github Actions: https://github.com/actions/starter-workflows/blob/master/ci/npm-publish.yml.

**Comment by ryhinchey** [comment]
@tabrindle is this still something you're interested in doing?  Regardless, it'd be good to figure out release cadence as there's a decent amount in master that can be released in a new patch or minor version

**Comment by tabrindle** [comment]
Ideally, it would be done based on each PR landing in master, using conventional commits. I took care of the conventional commits part, one of you can set up the master ci build. Keep in mind, the npm publish requires a OTP from me - so it will have to be a prompt.

**Comment by gengjiawen** [comment]
> Keep in mind, the npm publish requires a OTP from me - so it will have to be a prompt.

It should work with token even enabled with OTP from my understanding.
