### ISSUE TITLE
Version prints `undefined`

### ISSUE THREAD

**Issue by marvinhagemeister** [tabrindle/envinfo#112]
The current code assumes that `/etc/os-release` file will always have a `VERSION=xxx` entry on linux based systems. This is not true for a rolling distro like Arch linux.

The code in `envinfo` will fallback to an empty array if that's the case, but it still assumes that the array has two entries one line later.

https://github.com/tabrindle/envinfo/blob/120a367c1c89698a18114cdf32c86b29f813fd1f/src/helpers/system.js#L46-L47

Out of bound accesses in JS return `undefined` which will be cast to a `string` in the template literal. This leads to the following output on my system:

```
Linux 5.2 Arch Linux undefined
```

**Comment by tabrindle** [comment]
Nice catch and thanks for debugging that! What would recommend as an alternative for your distro?

**Comment by marvinhagemeister** [comment]
I don't think there is an alternative because `Arch Linux` has no version number at all. I'd just leave it blank and only print the OS:

```bash
Linux 5.2 Arch Linux
```

The kernel version is somewhat of a loose indication, but again it doesn't say anything about how recent the Arch image is.

**Comment by ryhinchey** [comment]
pretty sure this issue can be closed after looking at this merged PR :) 
https://github.com/tabrindle/envinfo/pull/123

**Comment by ryhinchey** [comment]
This is still an issue.  I just pulled the latest archlinux [docker image](https://hub.docker.com/_/archlinux/) and there is no `/etc/os-release` which makes envinfo crash

**Comment by ryhinchey** [comment]
closing this issue in favor of https://github.com/tabrindle/envinfo/issues/190
