### ISSUE TITLE
envinfo can`t print npmpackages info on windows10.0

### ISSUE THREAD

**Issue by Issacpeng** [tabrindle/envinfo#135]
![image](https://user-images.githubusercontent.com/11417652/69598352-08391280-1044-11ea-907a-e1b0dc230a7c.png)

**Comment by tabrindle** [comment]
It is not default to get npm packages - local or global. You have to add the option `--npmPackages`

Check out the difference between `npx envinfo --npmPackages` and `npx envinfo`
