### ISSUE TITLE
rust version info

### ISSUE THREAD

**Issue by gengjiawen** [tabrindle/envinfo#136]
Current it's info is from `rustup`, I think it's more accurate from `rustc`.
```console
  Languages:
    Rust: 1.20.2 - /root/.cargo/bin/rustup
```

**Comment by tabrindle** [comment]
Agreed. I think I have a branch somewhere where I fixed this, but it's clearly not merged.

**Comment by gengjiawen** [comment]
> Agreed. I think I have a branch somewhere where I fixed this, but it's clearly not merged.

https://github.com/tabrindle/envinfo/tree/bugfix/rust looks like this is the branch

**Comment by gengjiawen** [comment]
Also, I think we can remove windows limitation since it also works on windows.
