### ISSUE TITLE
support visual studio version for windows

### ISSUE THREAD

**Issue by gengjiawen** [tabrindle/envinfo#155]

**Comment by tabrindle** [comment]
Agreed. While I can't/won't test this, I'd approve a well tested PR

**Comment by gengjiawen** [comment]
I intend to use https://github.com/microsoft/vswhere. It's officially supported by microsoft.

**Comment by asklar** [comment]
We would definitely use this within React Native for Windows. @gengjiawen are you still looking at implementing this? are you blocked on anything?

**Comment by tabrindle** [comment]
Feel free to make a PR 👍
