### ISSUE TITLE
Failed to run on Windows 2019 in Github Actions

### ISSUE THREAD

**Issue by motss** [tabrindle/envinfo#157]
## Description

When running the CLI in Github Actions, it unexpectedly failed to run in only `windows-2019`.

## Versions

*envinfo*: 7.5.0
*OS*: windows-2019 in Github Actions

## Steps to reproduce

1. Setup a Github Actions and run `npx envinfo`.
2. The process exits when executing the command:

    ```sh
    npx: installed 1 in 2.319s
    ##[error]Process completed with exit code 1.
    ```

**Comment by ryhinchey** [comment]
@motss are there any other logs available that you could add here that could help us debug?

**Comment by tabrindle** [comment]
Try setting ENVINFO_DEBUG=trace before running.
-- 
Trevor Brindle
Software Engineer
C: +1 407 450 8700

**Comment by motss** [comment]
It turns out to be another command error. `envinfo` is working great on Windows in Github Actions! 👍

**Comment by tabrindle** [comment]
Thanks for the update!

-- 
Trevor Brindle
Software Engineer
C: +1 407 450 8700
