### ISSUE TITLE
Consolidate CI to GH Actions

### ISSUE THREAD

**Issue by ryhinchey** [tabrindle/envinfo#167]
We currently have appveyor, circle, and Travis.  I think we could consolidate all of these into github actions. 

@tabrindle do you have any initial objections with this?  I think it’d be easier to maintain and I don’t see the need for these separate CI services.

**Comment by ryhinchey** [comment]
As discussed [here](https://github.com/tabrindle/envinfo/pull/166#issuecomment-627675159), we intend to keep Circle and consolidate Travis & Appveyor into Github Actions

**Comment by tabrindle** [comment]
Recent PR has github actions added, take a look. Looks good to me.

**Comment by ryhinchey** [comment]
closing this issue as github actions were added https://github.com/tabrindle/envinfo/pull/180
