### ISSUE TITLE
Does not recognize Android SDK on mac

### ISSUE THREAD

**Issue by hidde-jan** [tabrindle/envinfo#168]
Android studio on 3.6.3 installs command line tools in `$USER/Library/Android/sdk/cmdline-tools/latest/bin` instead of `$USER/Library/Android/sdk/tools/bin`. This means it can't find `sdkmanager` if the `ANDROID_HOME` variable is set.

**Comment by ryhinchey** [comment]
@hidde-jan What OS are you on? And thanks for reporting this!

**Comment by hidde-jan** [comment]
The new `ndk` directory is also no longer `$ANDROID_HOME/ndk-bundle`, but `$ANDROID_HOME/ndk/<version>`. I guess this is due to the new Sidy-by-side install method, where you can have multiple versions of the ndk installed.

**Comment by IvanaGyro** [comment]
Here is [extra information](https://stackoverflow.com/questions/47150410/failed-to-run-sdkmanager-list-with-java-9). The reason that `$USER/Library/Android/sdk/tools/bin` cannot be used is that OpenJDK 13 and Java 11 (or above) do not implement some functions used by the programs in `$USER/Library/Android/sdk/tools/bin`.

**Comment by cortinico** [comment]
Just a heads up that I believe this has been implemented:
https://github.com/tabrindle/envinfo/blob/7fe97eab8054a2ea81d822eeba79aff0b4afd9c9/src/helpers/sdks.js#L14-L20

and this issue can be closed
