### ISSUE TITLE
Build failure on Node 6, 8, and 9

### ISSUE THREAD

**Issue by tabrindle** [tabrindle/envinfo#172]
Looks like its related to required engines for a few underlying devdependencies. 

envinfo doesn't actually have to build on those versions, just run. We can either drop them from PR builds, and test what is published, or mark the failing dependencies as optional.

**Comment by gengjiawen** [comment]
tbh it's not sustainable in the long run since they are not maintained anymore.

**Comment by ryhinchey** [comment]
The builds are passing now on these environments

**Comment by gengjiawen** [comment]
> The builds are passing now on these environments

You pr looks like forget cirecle ci. The build failed.

**Comment by gengjiawen** [comment]
Also I do thinks `--ignore-engines` is not a good idea. we add engines to `package.json` because it needs the right engine.

**Comment by ryhinchey** [comment]
> > The builds are passing now on these environments
> 
> You pr looks like forget cirecle ci. The build failed.

@gengjiawen do you have an example of a failed build in circle? I can't seem to find any.  Circle also uses `npm` instead of `yarn`.  It should probably use yarn for consistency

**Comment by ryhinchey** [comment]
> Also I do thinks `--ignore-engines` is not a good idea. we add engines to `package.json` because it needs the right engine.

@gengjiawen agree it felt a hacky.  Here are the options I explored when making the decision to ignore engines during the build:

1. release a new major version of envinfo supporting node 10 and above
2. only run the build on node 10 and above
3. use `--ignore-engines` during the build

I think it's reasonable to expect envinfo to work on at least node 8 so 1 was not a realistic option.  

For 2, I feel that we should always run our builds on the node versions we support.  

That left me with option 3.

If there's a better option, I'm all for it.

**Comment by tabrindle** [comment]
So the question here is whether envinfo will run (not necessarily build) on older versions - and realistically, as long as we CAN support them, we should. 

I say we move to building on node 10 and above, and the other ci jobs run the most recently published version of envinfo to check them.

**Comment by gengjiawen** [comment]
> > > The builds are passing now on these environments
> > 
> > 
> > You pr looks like forget cirecle ci. The build failed.
> 
> @gengjiawen do you have an example of a failed build in circle? I can't seem to find any. Circle also uses `npm` instead of `yarn`. It should probably use yarn for consistency

CircleCI can run by yarn, you need to change here: https://github.com/tabrindle/envinfo/blob/f2c91a6f73aefc8ddce8e5142d15014799775447/.circleci/config.yml#L26.

Current failed link: https://app.circleci.com/pipelines/github/tabrindle/envinfo/106/workflows/bf22ad35-bccf-4010-891c-1dd83a526c94/jobs/561/steps

> So the question here is whether envinfo will run (not necessarily build) on older versions - and realistically, as long as we CAN support them, we should.

Currently we can run on old version. My main concern is than in the long run it might cause too much maintain burden.
