### ISSUE TITLE
Publish a new NPM release

### ISSUE THREAD

**Issue by mxschmitt** [tabrindle/envinfo#177]
Hey, would be awesome if a new NPM release could be published since a few more presets were added and they won't work until they are published.

Thanks, great tool!

Relates to this: https://github.com/microsoft/playwright/pull/2237

**Comment by tabrindle** [comment]
Done! Sorry for the delay, lot's going on right now. 

https://github.com/tabrindle/envinfo/releases/tag/7.6.0
