### ISSUE TITLE
Improve the `envinfo.run` works with async/await

### ISSUE THREAD

**Issue by vanpipy** [tabrindle/envinfo#199]
Hi,

The `envinfo.run` cannot work with async/await currently, which is a little bit inconvenient to use it programlly. Or it is not the right way to use it?

Thanks :D.

**Comment by ryhinchey** [comment]
It should work fine with async/await.  Mind sharing some code that isn't working for you?

**Comment by vanpipy** [comment]
Sorry for this because I take the code here.

https://github.com/tabrindle/envinfo/blob/42d3ca7ee7ea6b21143b7154156b9e18a64cdaf5/src/envinfo.js#L144

So close it and thanks!

**Comment by ryhinchey** [comment]
yah it's a few levels down but `run` does eventually return a `Promise`.
