### ISSUE TITLE
Wrong Version of Windows

### ISSUE THREAD

**Issue by stanleyowen** [tabrindle/envinfo#209]
It seems like running the `npx envinfo` command, it returns the wrong operating system (since I recently upgraded it to Windows 11).

Here is the output:
```js
System:
    OS: Windows 10 10.0.22000 // It is expected to be Windows 11 instead of Windows 10
    CPU: (4) x64 AMD Ryzen 3 4300U with Radeon Graphics
    Memory: 1.33 GB / 7.37 GB
...
```

Steps to Reproduce
1. Open terminal
2. Type `npx envinfo`
3. See the error

**Comment by gengjiawen** [comment]
It's using `os.release()` ,you should report to Node.js.https://github.com/tabrindle/envinfo/blob/f1cd4da617082a5a278e6ea5e5d7ea09f6ee3a98/src/helpers/system.js#L51

**Comment by stanleyowen** [comment]
Additionally, `os.release()` only returns the OS's version number, which its version is appropriate with the system settings, however it just returns `Windows 10 10.0.22000`  instead of `Windows 11 10.0.22000`.
