### ISSUE TITLE
feat: add pnpm option in Binaries

### ISSUE THREAD

**Issue by rishabh3112** [tabrindle/envinfo#216]
Hi Trevor @tabrindle,

At webpack-cli, we need information of `pnpm` installations of user submitting issues with `pnpm` as package manager.
Raised this issue to know whether this would be a welcome addition. If so, I can create a PR for the same 😄.

PR at webpack-cli for reference: 
https://github.com/webpack/webpack-cli/pull/3072
https://github.com/webpack/webpack-cli/pull/3072/files

Thanks and Regards,
Rishabh Chawla.

**Comment by rishabh3112** [comment]
Friendly ping @tabrindle 😄

**Comment by alexander-akait** [comment]
@gengjiawen friendly ping

**Comment by gengjiawen** [comment]
PR is welcome. For now I don't have time for this.

**Comment by raulfdm** [comment]
Hey peps... 👋 

Is it something missing to add this feature?
