### ISSUE TITLE
Firefox is not detected

### ISSUE THREAD

**Issue by thany** [tabrindle/envinfo#221]
I'm on Windows 10, and have Firefox 98.0.1 installed. Just through the regular installer. Nothing special. It's not detected.

As far as I know, it's been like this forever. I cannot remember a time where Firefox *was* properly detected... So it must've been years ago, if ever 😯

I'm on the profile "default", auto update working fine, no weird installation options used, it's in the default installation directory. I honestly can't say what would be different about it on my pc, than it would be on any other.

```text
C:\>npx envinfo --system OS --browsers --binaries

  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 16.74 GB / 31.76 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 99.0.4844.51
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.39)
    Internet Explorer: 11.0.19041.1202
```

Even though, there it is:

![image](https://user-images.githubusercontent.com/152227/158358737-450c508a-d2ce-4cb0-b0e2-3b97fef478fc.png)

It probably goes without saying, if I install Waterfox, that one isn't detected either.

**Comment by SetTrend** [comment]
The bug is in this line:

https://github.com/tabrindle/envinfo/blob/7fe97eab8054a2ea81d822eeba79aff0b4afd9c9/src/helpers/browsers.js#L115

**Comment by thany** [comment]
Same for Firefox Developer Edition. Not sure if it is meant to detect varieties of a browser, like Chrome Canary or Edge Dev, but saying just in case.

**Comment by SetTrend** [comment]
Would you mind running the following commands in PowerShell:

```powershell
$filePath = 'C:\Program Files.....'
. $filePath -v | Write-Output
```
_(Please replace the above ellipsis with the absolute path to Firefox Developer Edition.)_

I am then going to implement handling that edition into my pull request.

**Comment by thany** [comment]
This what you mean?

```
PS> $filePath = 'C:\Program Files\Firefox Developer Edition\firefox.exe'
PS> . $filePath -v | Write-Output
Mozilla Firefox 113.0b9
```

**Comment by SetTrend** [comment]
All done now. Let's hope contributors here, like @gengjiawen, will be happy with the change and merge the result.

**Comment by gengjiawen** [comment]
My PR still pending for merge. So got contact with @tabrindle is the way.

**Comment by SetTrend** [comment]
@thany, @gengjiawen, @alexander-akait:

It looks like this repository's owner, @tabrindle, has either died or quit the repository.

This repository is worthless if it reports incorrect and insufficient data. WebPack depending on this repository.

So, should be fork this project and continue on that fork?

**Comment by tabrindle** [comment]
Reports of my death are greatly exaggerated, but I thank you for your contribution and concern for my wellbeing.

**Comment by SetTrend** [comment]
Thanks a lot for replying and merging the pull request, @tabrindle!

Sorry for Trumping 😉
