### ISSUE TITLE
Use pkg to distribute binary outside npm

### ISSUE THREAD

**Issue by sergiodxa** [tabrindle/envinfo#41]
This module is awesome, but is tied to having npm installed. Using [pkg](https://github.com/zeit/pkg) would be possibly to generate binaries for Windows, Linux and Mac and distribute them outside npm (like GitHub releases) or even `brew` and similar tools.

**Comment by tabrindle** [comment]
This is a great idea - I actually have some experiments stashed with pkg and another similar framework, but the binaries are relatively huge, and would require a couple of my helpers to be rewritten. 

I'd be happy to accept a PR if you want to work on it!

**Comment by tabrindle** [comment]
@sergiodxa Try this out! https://github.com/tabrindle/envinfo/releases/tag/5.5.0

**Comment by sergiodxa** [comment]
Awesome!
