### ISSUE TITLE
Not detecting Perl language

### ISSUE THREAD

**Issue by alichtman** [tabrindle/envinfo#48]
<img width="716" alt="image" src="https://user-images.githubusercontent.com/20600565/40691854-44e29600-637c-11e8-9538-0c97f4cf8299.png">

**Comment by tabrindle** [comment]
🤔is this the built-in macos Perl? If not, how and where is is it installed?

**Comment by alichtman** [comment]
> is this the built-in macos Perl?

Yep.

You can find it at: `usr/bin/perl`

**Comment by tabrindle** [comment]
I thought I had added it, apparently not. Expect a new release sometime later today 👍
