### ISSUE TITLE
--clipboard option fails on Windows

### ISSUE THREAD

**Issue by Hexxeh** [tabrindle/envinfo#57]
clipboardy, the dependency used for clipboard support, bundles native binaries to write to the clipboard. Unfortunately, these are lost during the webpacking process this tool uses. This means that running envinfo --clipboard fails at runtime on Windows.

**Comment by tabrindle** [comment]
😭 Thank you so much for reporting and finding this issue! 2 questions:

1. Does this prevent envinfo from printing the info?
2. Is there an alternative to using native binaries for clipboard support on node/windows?

**Comment by Hexxeh** [comment]
1. Yes
2. Older versions of clipboardy used a non-native way of doing this, so pinning an older version might be one approach. They switched because of issues with large amounts of data in clipboard, but that isn't such concern here.

**Comment by tabrindle** [comment]
1. Crap.
2. Awesome. 

Would you be willing to PR/test that version change?

**Comment by Hexxeh** [comment]
The old version of clipboardy has bad Unicode support, not sure if that's an issue for this particular dependency.

The real fix would probably be to publish a non-webpacked version and include a dependency on clipboardy. Might not be appropriate for some of the ways this library is being distributed though.

**Comment by zacanger** [comment]
Since this is meant to be used in Node, running Webpack over the source isn't really providing much benefit (no need to minify code if it's not getting delivered to a browser). I'd be happy to put in a PR changing the build.

**Comment by tabrindle** [comment]
envinfo is most useful when used via npx - and webpack enables a much smaller footprint and shorter download time. In my benchmarks before publishing it, it reduced type from initial command to report by several seconds. 

An alternate solution might be to use npx to call clipboardy - especially since it's not always used, and only a problem on windows.

**Comment by tabrindle** [comment]
Working on moving the dependency to npx to be installed correctly without being in the main envinfo bundle.
