### ISSUE TITLE
VSCode detection Not Found but it s there

### ISSUE THREAD

**Issue by jmfrancois** [tabrindle/envinfo#58]
You will have lots of info following screenshots>
Just missing.
I have used npx to execute
node is installed using nvm.

<img width="1093" alt="screen shot 2018-09-17 at 13 15 55" src="https://user-images.githubusercontent.com/19857479/45620127-01943000-ba7c-11e8-9f57-67d14e52340d.png">

After reading the code, its based on the feature: add "code" to the env PATH.
which was not the case on my laptop.

Could we make that test more bullet proof ?

**Comment by tabrindle** [comment]
Thanks for the report! This is actually on the todo list - add a fallback method of detection for code using the same method envinfo uses for other applications in your /Applications folder.

**Comment by tabrindle** [comment]
Adding in a duplicate check for vscode via command line tool as well as bundle id.
