### ISSUE TITLE
Adding babel 7

### ISSUE THREAD

**Issue by gengjiawen** [tabrindle/envinfo#69]
With babel we can write more modern js using feature like esm.
Also jest can use babel too.

**Comment by tabrindle** [comment]
The original intention of the project was to stay as compatible as possible without a transpile build step.

At this point, you're probably right. I will look into this.

**Comment by gengjiawen** [comment]
Thanks for consideration. My first implementation is es6 in this feature https://github.com/tabrindle/envinfo/pull/70. But I have can't pass the eslint. Reverting to es5 and commonjs is quite pain in my experience.

**Comment by tabrindle** [comment]
Merged!
