### ISSUE TITLE
[Feature] Java version more precise.

### ISSUE THREAD

**Issue by gengjiawen** [tabrindle/envinfo#72]
Current: 
```bash
Java: 1.8.0 - /usr/bin/javac
```
New
```
Java: 1.8.0_192-b12 - /usr/bin/javac
```

**Comment by tabrindle** [comment]
Do we know the significance of the extra numbers and letters? For simplicity of reading and version extraction I left these addendums off, but will consider adding them back if they are actually important. In a semver world, these wouldn't be significant and aren't really necessary - they just clutter up the output and diffs. 

However, the helpers functions do have the ability to specify different regexes per function if necessary. 

Another thought - if we do this for Java we will need to investigate changing other helpers as well, such as Ruby.

**Comment by gengjiawen** [comment]
Java has many versions as you can see here https://www.oracle.com/technetwork/java/javase/8u-relnotes-2225394.html. The precise version will help us on this and should be default. 

I have run into issue certain jdk has some compile issue for android project.

About ruby, I am not familiar with the language but I can help with the java feature.

**Comment by tabrindle** [comment]
Ok, this makes sense. Feel free to make a PR for this. 

Turns out ruby is already correct and doing this:

```
npx envinfo --languages

  Languages:
    Bash: 4.4.23
    Go: 1.11.1
    PHP: 7.1.19
    Python: 2.7.10
    Ruby: 2.3.7p456
```

Thanks for writing up an issue.
