### ISSUE TITLE
[Bug] envinfo hang on node:alpine

### ISSUE THREAD

**Issue by gengjiawen** [tabrindle/envinfo#81]
```bash
docker run -it node:alpine /bin/sh
npm i -g envinfo && envinfo
```

**Comment by SimenB** [comment]
Interestingly, it does output if you hit `^C`

```sh-session
$ docker run -it node:alpine npx envinfo
npx: installed 1 in 1.353s
^C
  System:
    OS: Linux 4.9 Alpine Linux undefined
    CPU: (6) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 316.87 MB / 1.95 GB
    Container: Yes
    Shell: Unknown - /bin/ash
  Binaries:
    Node: 11.6.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.5.0-next.0 - /usr/local/bin/npm
```

It does hang up until hitting `^C`, though. And running it from `/bin/sh` within the image doesn't output even after `^C`. I have no idea why...

**Comment by tabrindle** [comment]
Looking into this now.

**Comment by tabrindle** [comment]
using `docker run -it -e ENVINFO_DEBUG=trace node:8 npx envinfo` I found the issue.

`getShellInfo` is hanging, possibly because of the type of shell - /bin/ash.

Working on a fix.

**Comment by gengjiawen** [comment]
@tabrindle This occurred again, can you reopen this ?

**Comment by tabrindle** [comment]
confirmed.

**Comment by borgogelli** [comment]
+1

**Comment by ryhinchey** [comment]
@tabrindle it looks like the work you did to fix this bug got reverted at some point.  I'll work on a PR adding it back soon!

**Comment by ryhinchey** [comment]
this issue can be closed given https://github.com/tabrindle/envinfo/pull/147 got merged

**Comment by karlhorky** [comment]
I guess the Alpine Linux tests were removed again in Feb 2024?

- https://github.com/tabrindle/envinfo/pull/247#issuecomment-2413975665

**Comment by karlhorky** [comment]
It seems like envinfo is hanging again on Alpine Linux:

- https://github.com/tabrindle/envinfo/issues/266
