### ISSUE TITLE
why was --clipboard removed?

### ISSUE THREAD

**Issue by sw-yx** [tabrindle/envinfo#83]
i see #57 but there wasnt really a discussion of why the clipboard option was removed. because i'm trying to make instructions for issue filers i cant assume people have clipboard-cli installed. just wondering why it seems to have been dropped because windows users have problems...

**Comment by tabrindle** [comment]
The problem in essence was compatibility across operating systems, and dealing with clipboards wasn't the main function of this library (though was becoming the biggest point of maintenance). The biggest factor is that dependencies are bundled and minified to make npx running faster, and clipboard libraries all seem to use OS specific binaries, which webpack can't handle in a JS script to my knowledge.

In the end, I made a choice to remove that option. Asking someone to highlight, copy and paste something is a lot less work than getting all the info envinfo gets manually. 

You could still always include directions to use `npx envinfo | pbcopy`.

Or, if you are hoping for a universal solution, just use npx on both commands. 

`npx envinfo  --system --binaries --markdown | npx clipboard-cli`

**Comment by tabrindle** [comment]
Two follow ups to this issue:

1. I will make sure there's an option to pipe the default format without escaping to the next binary, whether it be pbcopy, npx or something else. 
2. I will add this to the documentation. (Shame on me)

Sorry for any confusion or inconvenience

**Comment by sw-yx** [comment]
oooh i didnt know you could pipe npx’es like that (i was specifically even searching for that lol). sucks to be a bash noob.

thanks trevor

**Comment by tabrindle** [comment]
I've said it before, I'll say it again. npx is amazing.
